name: Integration-CI

env:
  TZ: Asia/Shanghai

# Controls when the workflow will run
on:
  push:
    branches:
      - main
      - nightly-update
    paths-ignore:
      - 'README.md'
      - 'DEV.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - 'steamDESC.txt'
  pull_request:
    branches:
      - main
      - nightly-update
    paths-ignore:
      - 'README.md'
      - 'DEV.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - 'steamDESC.txt'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3.3.0

      # Runs a single command using the runners shell
      - name: Run integration script
        run: ./main.bat

      - name: Upload generated files
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ETCLP
          path: mod.zip

  nightly-release:
    permissions: write-all
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/download-artifact@v3.0.2
        with:
          name: ETCLP

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-release"
          prerelease: true
          title: "test Build"
          files: |
            mod.zip
