name: Release

env:
  TZ: Asia/Shanghai

on:
  push:
    paths-ignore:
      - "README.md"
      - "DEV.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - "steamDESC.txt"
      - "website/**"
  pull_request:
    paths-ignore:
      - "README.md"
      - "DEV.md"
      - "CHANGELOG.md"
      - ".gitignore"
      - "steamDESC.txt"
      - "website/**"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run integration script
        run: ./main.bat

      - name: Upload generated files
        uses: actions/upload-artifact@v3
        with:
          name: ETCLP
          path: ETCLP.zip

  nightly-release:
    permissions: write-all
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/') != true
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ETCLP

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-release"
          prerelease: true
          title: "test Build"
          files: |
            ETCLP.zip

  release:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: ETCLP

      #- name: Unzip the artifact
      #  run: |
      #    mkdir temp
      #    unzip ETCLP.zip -d temp

      - name: Release Action
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ETCLP.zip
          body_path: CHANGELOG.md
          discussion_category_name: "公告"

      #- name: steam-workshop-upload
      #  uses: Weilbyte/steam-workshop-upload@v1.1
      #  with:
      #    appid: 236850 # Game's Steam App ID
      #    itemid: 2897275182 # Your mod's Steam Workshop ID
      #    path: 'temp'
      #  env:
      #    STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
      #    STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password
      #    STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }} # Your Steam Guard 2FA shared secret (Optional)
