name: Release

env:
  TZ: Asia/Shanghai

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - name: Run integration script
        run: ./main.bat
        
      - name: Upload generated files
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ETCLP
          path: mod.zip
      
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
        
      - uses: actions/download-artifact@v3.0.2
        with:
          name: ETCLP
      
      - name: Unzip the artifact
        run: |
          mkdir temp
          unzip mod.zip -d temp 
      
      - name: Release Action
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            mod.zip
          body_path: CHANGELOG.md
          discussion_category_name: "公告"
          
      #- name: steam-workshop-upload
      #  uses: Weilbyte/steam-workshop-upload@v1.1
      #  with:
      #    appid: 236850 # Game's Steam App ID
      #    itemid: 2897275182 # Your mod's Steam Workshop ID
      #    path: 'temp'
      #  env:
      #    STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} # Your Steam username
      #    STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }} # Your Steam password
      #    STEAM_TFASEED: ${{ secrets.STEAM_TFASEED }} # Your Steam Guard 2FA shared secret (Optional)