name: update-nightly

on:
  #runs at 11:10 UTC every day
  #11:10 UTC = 19:10 CST (China Standard Time)
  schedule:
    - cron: '10 11 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch branch
        run: git checkout -b nightly-update

      - name: Get the output zip
        run: |
          curl -X 'GET' \
            'https://paratranz.cn/api/projects/5342/artifacts/download' \
            -H 'accept: */*' \
            -H 'Authorization: ${{ secrets.PARATRANZ_API_TOKEN }}' -L --output text.zip

      - name: Cleanup the folder
        run: |
          rm -r cn_text
          mkdir cn_text

      - name: Unzip
        run: |
          mkdir temp
          unzip text.zip -d temp
          cp temp/special/* cn_text/ -r
          cp temp/chars.txt .

      - name: Cleanup the folder
        run: |
          rm -r temp

      - name: Setup git user
        uses: fregante/setup-git-user@v2

      - name: Commit Changes & Push to Remote Branch
        run: |
          git add -A
          git commit -m "upd: update translated text nightly

          Co-authored-by: Cccc_ <47687154+Cccc-owo@users.noreply.github.com>
          Co-authored-by: shuaichao189 <38562980+shuaichao189@users.noreply.github.com>
          Co-authored-by: Zhujianfei1 <98221113+Zhujianfei1@users.noreply.github.com>
          Co-authored-by: CH. <54112189+CHuang227@users.noreply.github.com>
          Co-authored-by: Fritzwang <122777315+Fritzwang@users.noreply.github.com>
          Co-authored-by: 15910637182 <122958141+15910637182@users.noreply.github.com>
          Co-authored-by: IsaacChen0527 <41335976+IsaacChen0527@users.noreply.github.com>
          Co-authored-by: bamboo river <79087199+zhuxizheng@users.noreply.github.com>
          Co-authored-by: Observl <63183098+Observl@users.noreply.github.com>
          Co-authored-by: Cloudflipper <123280088+Cloudflipper@users.noreply.github.com>
          Co-authored-by: Kar0606 <123638219+Kar0606@users.noreply.github.com>
          Co-authored-by: 止波里 <70061078+Chiangkaisheck@users.noreply.github.com>
          Co-authored-by: 虛白Lemon <104324132+VoidLemon@users.noreply.github.com>
          Co-authored-by: SphinX1633 <94877214+SphinX1633@users.noreply.github.com>
          Co-authored-by: ESOSK <136055019+ESOSK@users.noreply.github.com>
          Co-authored-by: kidding <76855840+areukiiiddingme@users.noreply.github.com>
          Co-authored-by: cielow <40722647+cielow@users.noreply.github.com>
          Co-authored-by: fatyu101 <151294765+fatyu101@users.noreply.github.com>"
          git push -u origin nightly-update -f
