# This is a basic workflow that is manually triggered

name: Update-Website-Package

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: '00 9 * * SAT'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Update-Dependices:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # submodules: true

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7
          run_install: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: website/package.json

      - name: Update
        run: |
          rm pnpm-lock.yaml
          pnpm run docs:update-package

      - uses: fregante/setup-git-user@v2.0.0

      - name: Commit Changes & Push to Remote Branch
        run: |
          git add -A
          git commit -m "chore: update deps"
          git push -u origin
