name: update-52-text

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch branch
        run: git checkout -b update-52-text

      - name: Get the output zip
        run: |
          curl -X 'GET' \
            'https://paratranz.cn/api/projects/2/artifacts/download' \
            -H 'accept: */*' \
            -H 'Authorization: ${{ secrets.PARATRANZ_API_TOKEN }}' -L --output text.zip

      - name: Cleanup the folder
        run: |
          rm -r cn_text
          mkdir cn_text

      - name: Unzip
        run: |
          mkdir temp
          unzip text.zip -d temp
          cp temp/utf8/* cn_text/ -r

      - name: Cleanup the folder
        run: |
          rm -r temp

      - name: Setup git user
        uses: fregante/setup-git-user@v2

      - name: Commit Changes & Push to Remote Branch
        run: |
          git add -A
          git commit -m "upd: update Chinese Language Mod"
          git push -u origin update-52-text -f
